name: gh-pages

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run html build
        run: |
          make html
          touch build/html/.nojekyll

      - name: Deploy to GH-Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build/html
